---
- name: install/upgrade package
  become: yes
  yum:
    name: nginx
    state: latest
  notify: restart nginx

- name: enable permanently
  become: yes
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: configure nginx
  become: yes
  template:
    source: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
  notify: reload nginx